namespace Genbox.HttpBuilders.Enums;

/// <summary>Media type as defined by IANA. See https://www.iana.org/assignments/media-types/media-types.xhtml</summary>
public enum MediaType
{
    Unknown = 0,
    Application_gzip,
    Application_json,
    Application_msword,
    Application_octetstream,
    Application_ogg,
    Application_pdf,
    Application_php,
    Application_rtf,
    Application_xml,
    Application_zip,
    Audio_3gpp,
    Audio_3gpp2,
    Audio_aac,
    Audio_midi,
    Audio_mpeg,
    Audio_ogg,
    Audio_opus,
    Audio_wav,
    Audio_webm,
    Font_otf,
    Font_ttf,
    Font_woff,
    Font_woff2,
    Image_bmp,
    Image_gif,
    Image_jpeg,
    Image_png,
    Image_tiff,
    Image_webp,
    Text_calendar,
    Text_css,
    Text_csv,
    Text_html,
    Text_javascript,
    Text_plain,
    Text_xml,
    Video_3gpp,
    Video_3gpp2,
    Video_mp2t,
    Video_mpeg,
    Video_ogg,
    Video_webm
}