name: Nuget release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Pack release
        run: dotnet pack -c Release src/HttpBuilders.sln -o Temp
      - name: Upload to nuget
        run: dotnet nuget push --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json Temp/*.nupkg